import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, Eye, EyeOff, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Logo } from "@/components/localfix/logo";
export const Route=createFileRoute("/auth")({head:()=>({meta:[{title:"Sign in — localFix"},{name:"description",content:"Sign in to save repair assessments, photos, and guide progress."},{property:"og:title",content:"Sign in — localFix"},{property:"og:description",content:"Keep every repair in one place."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Auth});
function Auth(){const navigate=useNavigate();const [mode,setMode]=useState<"signin"|"signup">("signin");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const result=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+"/dashboard"}});setBusy(false);if(result.error){setMessage(result.error.message);return}if(mode==="signup"&&!result.data.session){setMessage("Check your email to confirm your account.");return}navigate({to:"/dashboard"})}async function google(){setBusy(true);const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin});if(result.error){setMessage(result.error.message);setBusy(false);return}if(!result.redirected)navigate({to:"/dashboard"})}
return <main className="grid min-h-screen lg:grid-cols-[.9fr_1.1fr]"><section className="flex min-h-screen flex-col px-5 py-6 sm:px-12 lg:px-20"><div className="flex items-center justify-between"><Link to="/"><Logo/></Link><Button asChild variant="ghost" size="sm"><Link to="/"><ArrowLeft/>Home</Link></Button></div><div className="mx-auto my-auto w-full max-w-md py-12"><p className="section-label">Your repair history</p><h1 className="mt-3 font-display text-4xl font-bold">{mode==="signin"?"Welcome back.":"Keep your repairs together."}</h1><p className="mt-3 text-muted-foreground">{mode==="signin"?"Sign in to continue where you left off.":"Create an account to save assessments, photos, and progress."}</p><Button variant="outline" className="mt-8 h-12 w-full" onClick={google} disabled={busy}><span className="text-lg font-bold">G</span>Continue with Google</Button><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>or use email<span className="h-px flex-1 bg-border"/></div><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="email">Email</Label><Input id="email" className="mt-2 h-12" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></div><div><Label htmlFor="password">Password</Label><div className="relative mt-2"><Input id="password" className="h-12 pr-11" type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required autoComplete={mode==="signin"?"current-password":"new-password"}/><Button type="button" variant="ghost" size="icon" className="absolute right-1.5 top-1.5" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff/>:<Eye/>}</Button></div></div>{message&&<p className="rounded-md bg-muted p-3 text-sm" role="status">{message}</p>}<Button className="h-12 w-full" disabled={busy}>{busy&&<Loader2 className="animate-spin"/>}{mode==="signin"?"Sign in":"Create account"}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">{mode==="signin"?"New to localFix? ":"Already have an account? "}<button className="font-bold text-primary" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMessage("")}}>{mode==="signin"?"Create an account":"Sign in"}</button></p></div></section><aside className="relative hidden overflow-hidden bg-foreground p-16 text-background lg:flex lg:flex-col lg:justify-end"><div className="absolute inset-0 pattern-grid opacity-15"/><div className="relative max-w-lg"><span className="grid size-14 place-items-center rounded-lg bg-primary text-primary-foreground"><Logo inverse/></span><h2 className="mt-10 font-display text-5xl font-bold leading-tight">Every repair remembers where you left off.</h2><p className="mt-5 text-lg leading-8 text-primary-foreground/60">One place for symptoms, photos, assessments, guides, and trusted professionals.</p></div></aside></main>}
