import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CheckCircle2, Filter, MapPin, Search, Send, Star } from "lucide-react";
import { AppShell } from "@/components/localfix/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { professionals } from "@/lib/localfix-data";
export const Route=createFileRoute("/professionals")({head:()=>({meta:[{title:"Find a repair professional — localFix"},{name:"description",content:"Compare trusted local repair professionals and request a quote."},{property:"og:title",content:"Find a repair professional — localFix"},{property:"og:description",content:"Find the right expert for your repair."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Professionals});
function Professionals(){return <AppShell eyebrow="Professional network" title="Find the right repairer"><div className="mx-auto max-w-6xl"><div className="rounded-lg bg-foreground p-6 text-background sm:p-8"><div className="max-w-2xl"><h2 className="font-display text-2xl font-bold">Share the assessment, not the whole story again.</h2><p className="mt-2 text-sm text-primary-foreground/60">Professionals receive the item, symptoms, safety notes, and checks you already completed.</p></div><div className="mt-6 flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-primary-foreground/50"/><Input className="h-12 border-primary-foreground/20 bg-primary-foreground/10 pl-11 text-background placeholder:text-primary-foreground/45" placeholder="Computer, bicycle, appliance…"/></div><div className="relative sm:w-56"><MapPin className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-primary-foreground/50"/><Input className="h-12 border-primary-foreground/20 bg-primary-foreground/10 pl-11 text-background" value="Central District" readOnly/></div><Button className="h-12 bg-background text-foreground hover:bg-background/90"><Search/>Search</Button></div></div><div className="mt-6 flex items-center justify-between"><p className="text-sm text-muted-foreground">3 verified professionals nearby</p><Button variant="outline" size="sm"><Filter/>Filters</Button></div><div className="mt-4 grid gap-4 lg:grid-cols-3">{professionals.map(pro=><article key={pro.id} className="rounded-lg border bg-background p-5"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-full bg-secondary font-bold text-primary">{pro.initials}</span><span className="inline-flex items-center gap-1 text-sm font-bold"><Star className="size-4 fill-warning text-warning"/>{pro.rating}</span></div><div className="mt-6 flex items-center gap-2"><h2 className="font-display text-lg font-bold">{pro.name}</h2><CheckCircle2 className="size-4 text-primary"/></div><p className="text-sm text-muted-foreground">{pro.business}</p><p className="mt-5 text-sm font-semibold">{pro.specialty}</p><dl className="mt-5 grid grid-cols-2 gap-3 border-y py-4 text-xs"><div><dt className="text-muted-foreground">Response</dt><dd className="mt-1 font-bold">{pro.response}</dd></div><div><dt className="text-muted-foreground">Price range</dt><dd className="mt-1 font-bold">{pro.price}</dd></div></dl><RequestButton name={pro.name}/></article>)}</div></div></AppShell>}
function RequestButton({name}:{name:string}){const [sent,setSent]=useState(false);return <Dialog><DialogTrigger asChild><Button className="mt-5 w-full">Request a quote</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{sent?"Request sent":"Request a quote from "+name}</DialogTitle><DialogDescription>{sent?"They’ll review your laptop assessment and reply with next steps.":"Your laptop power assessment will be included automatically."}</DialogDescription></DialogHeader>{sent?<div className="py-6 text-center"><CheckCircle2 className="mx-auto size-12 text-primary"/><p className="mt-4 font-bold">You’re all set.</p></div>:<><textarea className="min-h-28 rounded-md border p-3 text-sm outline-none focus:ring-2 focus:ring-ring" defaultValue="My MacBook Air won’t power on. I tested a known-good charger and there are no lights or sounds."/><Button onClick={()=>setSent(true)}><Send/>Send request</Button></>}</DialogContent></Dialog>}
