CREATE TYPE public.app_role AS ENUM ('customer', 'professional', 'admin');
CREATE TYPE public.repair_status AS ENUM ('draft', 'diagnosing', 'assessed', 'in_progress', 'completed');
CREATE TYPE public.request_status AS ENUM ('new', 'quoted', 'accepted', 'in_progress', 'completed', 'declined');
CREATE TABLE public.profiles (id uuid PRIMARY KEY, display_name text, city text, avatar_url text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Profiles are readable by owner" ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "Users can create own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL DEFAULT 'customer', UNIQUE (user_id, role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own roles" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
CREATE TABLE public.repair_guides (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, title text NOT NULL, category text NOT NULL, summary text NOT NULL, difficulty text NOT NULL, estimated_minutes integer NOT NULL, safety_level text NOT NULL DEFAULT 'standard', tools jsonb NOT NULL DEFAULT '[]'::jsonb, parts jsonb NOT NULL DEFAULT '[]'::jsonb, steps jsonb NOT NULL DEFAULT '[]'::jsonb, published boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.repair_guides TO anon, authenticated;
GRANT ALL ON public.repair_guides TO service_role;
ALTER TABLE public.repair_guides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Published guides are public" ON public.repair_guides FOR SELECT TO anon, authenticated USING (published = true);
CREATE TABLE public.professionals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid, name text NOT NULL, business_name text NOT NULL, city text NOT NULL, categories text[] NOT NULL DEFAULT '{}', rating numeric(2,1) NOT NULL DEFAULT 0, review_count integer NOT NULL DEFAULT 0, price_band text NOT NULL DEFAULT '$$', response_time text, verified boolean NOT NULL DEFAULT false, bio text, accepting_requests boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.professionals TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.professionals TO authenticated;
GRANT ALL ON public.professionals TO service_role;
ALTER TABLE public.professionals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Professional profiles are public" ON public.professionals FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Professionals manage own profile" ON public.professionals FOR ALL TO authenticated USING (owner_id = auth.uid() AND public.has_role(auth.uid(), 'professional')) WITH CHECK (owner_id = auth.uid() AND public.has_role(auth.uid(), 'professional'));
CREATE TABLE public.repairs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, item_name text NOT NULL, category text NOT NULL, symptom text NOT NULL, status public.repair_status NOT NULL DEFAULT 'draft', diagnosis jsonb, guide_id uuid REFERENCES public.repair_guides(id), progress integer NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100), photo_paths text[] NOT NULL DEFAULT '{}', notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.repairs TO authenticated;
GRANT ALL ON public.repairs TO service_role;
ALTER TABLE public.repairs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own repairs" ON public.repairs FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE TABLE public.repair_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), repair_id uuid NOT NULL REFERENCES public.repairs(id) ON DELETE CASCADE, customer_id uuid NOT NULL, professional_id uuid NOT NULL REFERENCES public.professionals(id), status public.request_status NOT NULL DEFAULT 'new', message text, quote_amount numeric(10,2), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.repair_requests TO authenticated;
GRANT ALL ON public.repair_requests TO service_role;
ALTER TABLE public.repair_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Customers read own requests" ON public.repair_requests FOR SELECT TO authenticated USING (customer_id = auth.uid());
CREATE POLICY "Customers create own requests" ON public.repair_requests FOR INSERT TO authenticated WITH CHECK (customer_id = auth.uid());
CREATE POLICY "Customers update own requests" ON public.repair_requests FOR UPDATE TO authenticated USING (customer_id = auth.uid()) WITH CHECK (customer_id = auth.uid());
CREATE POLICY "Professionals read assigned requests" ON public.repair_requests FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.professionals p WHERE p.id = professional_id AND p.owner_id = auth.uid()));
CREATE POLICY "Professionals update assigned requests" ON public.repair_requests FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.professionals p WHERE p.id = professional_id AND p.owner_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.professionals p WHERE p.id = professional_id AND p.owner_id = auth.uid()));
CREATE INDEX repairs_user_status_idx ON public.repairs(user_id, status);
CREATE INDEX requests_customer_idx ON public.repair_requests(customer_id, created_at DESC);
CREATE INDEX requests_professional_idx ON public.repair_requests(professional_id, created_at DESC);
CREATE INDEX professionals_city_idx ON public.professionals(city);